config/routes.rb
Rails.application.routes.draw do
  resources :sesai_people,
            path: 'pessoas-sesai',
            path_names: { new: 'cadastrar', edit: 'alterar', destroy: 'excluir' }

  resources :people,
            path: 'pessoas',
            path_names: { new: 'cadastrar', edit: 'alterar', destroy: 'excluir' }

  resources :budget_correction_factors
  resources :costs
  resources :investments

  post '/image-upload',     to: 'application#image_upload', as: :image_upload
  post '/procurar-pessoa',  to: 'people#search',            as: :search
  post '/procurar-pessoa-com-dsei', to: 'people#search_with_dsei', as: :search_with_dsei

  get 'category_budgets/index'

  resources :results, path: 'resultados', path_names: { new: 'cadastrar', edit: 'alterar' }
  resources :casais, path_names: { new: 'cadastrar', edit: 'alterar' }
  resources :absolute_data, path: 'dados-absolutos', path_names: { new: 'cadastrar', edit: 'alterar' }

  get '/pdsis/show', to: 'pdsis#show'

  scope '/dotacao-orcamentaria' do
    get '/', to: 'category_budgets#index', as: :category_budgets
    get '/alterar/:id',
        to: 'pdsis#edit_category_budgets',
        as: :edit_category_budget, defaults: { section: 'dotacao_orcamentaria' }
  end

  scope '/meu-pdsi' do
    post '/:id/alterar/projecao-orcamentaria/editar-justificativa',
         to: 'budget_justifiers#edit_justifier',
         as: :budget_justifier_edit_justifier

    post '/:id/alterar/projecao-orcamentaria/new_budget_forecast_by_cost',
         to: 'pdsis#new_budget_forecast_by_cost',
         as: :new_budget_forecast_by_cost

    post '/:id/alterar/projecao-orcamentaria/novo-comentario',
         to: 'budget_forecasts#new_comment',
         as: :budget_forecast_new_comment

    post '/:id/alterar/projecao-orcamentaria/ver-comentario',
         to: 'budget_forecasts#see_comment',
         as: :budget_forecast_see_comment

    post '/:id/alterar/projecao-orcamentaria/deleta-comentario',
         to: 'budget_forecasts#delete_comment',
         as: :budget_forecast_delete_comment

    post '/:id/alterar/projecao-orcamentaria/investimento/novo-comentario',
         to: 'budget_investments#new_comment',
         as: :budget_investment_new_comment

    post '/:id/alterar/projecao-orcamentaria/investimento/ver-comentario',
         to: 'budget_investments#see_comment',
         as: :budget_investment_see_comment

    post '/:id/alterar/projecao-orcamentaria/investimento/deleta-comentario',
         to: 'budget_investments#delete_comment',
         as: :budget_investment_delete_comment

    post '/:id/alterar/projecao-orcamentaria/update_cost_name',
         to: 'pdsis#update_cost_name',
         as: :update_cost_name

    get '/:id/alterar/projecao-orcamentaria/:subsection',
        defaults: { section: 'projecao-orcamentaria' },
        to: 'pdsis#edit',
        as: :edit_budget_projection

    get '/:id/alterar/resultados-esperados/:subsection',
        defaults: { section: 'resultados-esperados', tab: 'resultados' },
        to: 'pdsis#edit',
        as: :edit_results

    get '/:id/alterar/resultados-esperados/responsabilidades/:subsection',
        defaults: { section: 'resultados-esperados', tab: 'responsabilidades' },
        to: 'pdsis#edit',
        as: :edit_responsabilities

    get '/(ver/:section)',                    to: 'pdsis#index',      as: :pdsis
    patch '/:id/alterar/:section',            to: 'pdsis#update',     as: :pdsi
    get '/:id/alterar/:section(/:base_polo)', to: 'pdsis#edit',       as: :edit_pdsi
    delete '/:id/mapa/excluir',               to: 'pdsis#delete_map', as: :delete_map

    get '/:id/alterar/anexos/dimensionamento-necessidades/:subsection',
        defaults: { section: 'anexos' },
        to: 'pdsis#edit',
        as: :edit_anexos

    scope '/dados-demograficos' do
      patch '/:id/alterar', to: 'demographic_datas#update', as: :demographic_data
      get '/:id/alterar', to: 'demographic_datas#edit', as: :edit_demographic_data
    end

    scope '/indicadores-saude-indigena', defaults: { section: 'indicadores-saude-indigena' } do
      get '/:id/:subsection/alterar(/polo-base/:base_polo)(/casai/:casai)',
          to: 'pdsis#health_indicators',
          as: :health_indicators
    end

    # Resultados Esperados
    get '/:id/resultados-esperados',
        to: 'results_special#index', as: :results_special

    post '/:id/resultados-esperados',
         to: 'results_special#update', as: :results_special_edit

    post '/:id/resultados-esperados/loop',
         to: 'results_special#loop', as: :results_special_loop

    post '/:id/resultados-esperados/respontabilidade',
         to: 'results_special#responsability', as: :results_special_responsability

    post '/:id/resultados-esperados/nao-se-aplica',
         to: 'results_special#false_result', as: :results_special_false_result

    post '/:id/resultados-esperados/novo-comentario',
         to: 'results_special#new_comment', as: :results_special_new_comment

    post '/:id/resultados-esperados/deleta-comentario',
         to: 'results_special#delete_comment', as: :results_special_delete_comment

    post '/:id/resultados-esperados/delete',
         to: 'results_special#delete', as: :results_special_delete

    post '/:id/resultados-esperados/associar-produto',
         to: 'results_special#link_product', as: :results_special_link_product

    post '/:id/resultados-esperados/associar-produto-dsei',
         to: 'results_special#link_product_dsei', as: :results_special_link_product_dsei

    post '/:id/resultados-esperados/resultado-especifico',
         to: 'results_special#specific_result', as: :results_special_specific_result

    post '/:id/resultados-esperados/resultado-especifico/atualizar',
         to: 'results_special#specific_update', as: :results_special_specific_update

    post '/:id/resultados-esperados/resultado-especifico/deletar',
         to: 'results_special#delete_specific_result', as: :results_special_delete_specific_result

    post '/:id/resultados-esperados/ordenar-produtos',
         to: 'results_special#products_order', as: :results_special_products_order

    post '/:id/resultados-esperados/ver-comentario',
         to: 'results_special#see_comment', as: :results_special_see_comment

    post '/:id/resultados-esperados/selecionar-links',
         to: 'results_special#get_all_related_links', as: :results_special_get_all_related_links
    post '/:id/resultados-esperados/retirar-link',
          to: 'results_special#remove_link', as: :results_special_remove_link

    # Resultados Específicos
    get '/:id/resultados-especificos',
        defaults: { section: 'resultados-esperados', tab: 'especificos' },
        to: 'specific_results#edit',
        as: :edit_specific_results

    patch '/:id/resultados-especificos',
          defaults: { section: 'resultados-esperados', tab: 'especificos' },
          to: 'specific_results#update',
          as: :update_specific_results
    get '/:id/pdf', to: 'pdsis#render_pdf', as: :print_pdf
    get '/:id/pdf_errors', to: 'pdsis#pdf_errors', as: :pdf_errors
  end

  scope '/templates' do
    get '/',                        to: 'text_templates#index',   as: :text_templates
    patch '/:id/alterar/:section',  to: 'text_templates#update',  as: :text_template
    get '/:id/alterar/:section',    to: 'text_templates#edit',    as: :edit_text_template
    get '/introducao-sesai',        to: 'text_templates#introducao_sesai', as: :introducao_sesai
    get '/analise-situacional-sesai', to: 'text_templates#analise_situacional_sesai', as: :analise_situacional_sesai
    get '/processo-de-construcao-sesai', to: 'text_templates#processo_de_construcao_sesai', as: :processo_de_construcao_sesai
  end

  devise_for :users, path: '', path_names: { sign_in: 'entrar',
                                             sign_out: 'sair',
                                             password: 'secret',
                                             confirmation: 'verification',
                                             unlock: 'unblock',
                                             registration: 'register',
                                             sign_up: 'cmon_let_me_in' }

  resources :users, path: 'usuarios', path_names: { new: 'cadastrar', edit: 'alterar' }

  get '/alterar-senha',   to: 'users#edit_password',    as: :edit_password
  patch '/alterar-senha', to: 'users#update_password',  as: :update_password

  # ApplicationController Routes
  get '/health', to: 'application#health'
  post '/selecionar-dsei',
       to: 'application#set_dsei_and_pdsi_to_sesai',
       as: :set_dsei_and_pdsi_to_sesai

  post '/limpar-dsei',
       to: 'application#unset_dsei_and_pdsi_to_sesai',
       as: :unset_dsei_and_pdsi_to_sesai

  scope '/locations' do
    get '/villages', to: 'locations#villages'
    get '/cities', to: 'locations#cities'
  end

  root 'users#home'
end

app/helpers/pdsis_helper.rb
module PdsisHelper

  def allowed_sections
    %w"dados-fisiograficos destinos rede-servicos indicadores-saude-indigena destinos capacidade-instalada"
  end

  def section_path(section)
    three = [{ name: '3. Caracterização do DSEI', path: pdsis_path('caracterizacao-do-dsei')}]
    bread = [{ name: section_name(section), path: pdsis_path(section: section.gsub(/_/, '-'))}]

    if %w"mapa dados_fisiograficos destinos capacidade_instalada rede_servicos infraestrutura_edificacoes infraestrutura_saneamento capais".include? section
      three + bread
    else
      bread
    end
  end

  def section_name(section)
    {
      introducao: '1. Introdução',
      processo_de_construcao_do_pdsi: '2. O Processo de construção do PDSI',
      # 3
      caracterizacao_do_dsei: '3. Caracterização do DSEI',
      mapa: '3.1. Mapa do Território',
      dados_fisiograficos: '3.1. Dados fisiográficos',
      destinos: '3.2. Meios de Transporte',
      recursos_humanos: '3.2. Dimensionamento da força de trabalho',
      capacidade_instalada: '3.2. Capacidade Instalada',
      rede_servicos: '3.2. Rede de serviços',
      infraestrutura_edificacoes: '3.2. Infraestrutura de saúde - Edificações',
      infraestrutura_saneamento:  '3.2. Infraestrutura de saúde - Saneamento',
      capais:        '3.2. Infraestrutura de saúde - CAPAIs',
      # 4
      analise_situacional:        '4. Análise situacional',
      indicadores_saude_indigena: '4.1 Indicadores estratégicos para a saúde indígena',
      principais_desafios:        '4.2 Principais desafios a serem enfrentados em 2016-2019',
      # 5
      resultados_esperados:   '5. Resultados esperados',
      # 6
      projecao_orcamentaria:  '6. Projeção orçamentária 2016-2019',
      dotacao_orcamentaria:   '6. Dotação orçamentária',
      # 7
      anexos: '7. Anexos',
    }[section.to_sym]
  end

  def sum_human_resources(pdsi)
    sum_actual(pdsi)
    sum_needed(pdsi)
  end

  private

  def sum_needed(pdsi)
    needed = pdsi.pdsi_human_resources.select(:id,
                                              :ubsi_necessaria,
                                              :polo_base_tipo_1_necessaria,
                                              :polo_base_tipo_2_necessaria,
                                              :casai_necessaria,
                                              :sead_necessaria,
                                              :selog_necessaria,
                                              :sesane_necessaria,
                                              :sead_necessaria,
                                              :sgep_necessaria,
                                              :gabinete_necessaria,
                                              :diasi_necessaria)
    needed.all.as_json.each do |nd|
      id = nil
      nd.slice('id').values.each { |e| id = e }
      sum = nd.except('id').values.reject(&:nil?).sum
      PdsiHumanResource.find(id).update_attribute(:workforce_needed, sum)
    end
  end

  def sum_actual(pdsi)
    actual = pdsi.pdsi_human_resources.select(:id,
                                              :ubsi_atual,
                                              :polo_base_tipo_1_atual,
                                              :polo_base_tipo_2_atual,
                                              :casai_atual,
                                              :sead_atual,
                                              :selog_atual,
                                              :sesane_atual,
                                              :seofi_atual,
                                              :sgep_atual,
                                              :gabinete_atual,
                                              :diasi_atual)
    actual.all.as_json.each do |ac|
      id = nil
      ac.slice('id').values.each { |e| id = e }
      sum = ac.except('id').values.reject(&:nil?).sum
      PdsiHumanResource.find(id).update_attribute(:actual_sum, sum)
    end
  end
end

app/views/pdsis/_capacidade_instalada.html.slim
- @dsei.base_polos.each do |base_polo|
  fieldset
    legend
      |Polo Base &nbsp;
      strong = base_polo.name

    - nform_id = "emsis_#{base_polo.id}"
    div id=(nform_id)
      = f.fields_for :emsis do |emsi|
        = emsi.hidden_field :base_polo_id,  value: base_polo.id

        = render 'emsi_fields', { f: emsi }

    .right-align
      = link_to_add_association f, :emsis, { data: { "association-insertion-node": "##{nform_id}", "association-insertion-method": 'append' }, class: 'button btn-sm' } do
        = icon 'plus'
        | Adicionar EMSI

  /- break

app/views/pdsis/_caracterizacao_do_dsei.html.slim
h2 Caracterização do DSEI

.field
  = f.text_area :caracterizacao_do_dsei_3, { class: 'basic-editable' }

app/views/pdsis/_dados_fisiograficos.html.slim
- @dsei.base_polos_with_children.each do |base_polo|
  fieldset
    legend
      |Polo Base &nbsp;
      strong = base_polo.name

    = f.fields_for :pdsi_base_polo_data, base_polo.pdsi_data(@pdsi) do |item|
      = item.hidden_field :base_polo_id

      .field
        = item.label  :city_name
        = item.select :city_name, options_for_select(base_polo.cities, item.object.city_name), include_blank: true

    - base_polo.villages.each do |village|
      fieldset
        legend
          | Aldeia&nbsp;
          strong = village.name
        = f.fields_for :physiographic_datas, village.physiographic_datum(@pdsi) do |item|
          == render 'pdsis/physiographic_data/form', f: item

      /- break
  /- break

app/views/pdsis/_form.html.slim
= form_for @pdsi do |f|
  - if @pdsi.errors.any?
    #error_explanation.flash-error
      h2 = "#{pluralize(@pdsi.errors.count, "error")} encontrados"
      ul
        - @pdsi.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :processo_construcao_pdsi_2
    = f.text_area :processo_construcao_pdsi_2, { class: 'basic-editable' }
  .actions = f.submit

app/views/pdsis/_hidden_fields.slim
= hidden_field_tag 'section', params[:section]
= hidden_field_tag 'base_polo', @base_polo.id if @base_polo
= hidden_field_tag 'subsection', params[:subsection] if params[:subsection]
= hidden_field_tag 'casai', @casai.id if @casai
= hidden_field_tag 'tab', @tab if @tab

app/views/pdsis/_investment_item_fields.html.slim
tr.item data-category=("c#{f.object.budget_investment.investment.parent_id}-#{year}")
  td.action
  - if f.object.new_record?
    td.field
      div.err
        = f.text_field :name, class: 'new-record'
  - else
    td.field
      = f.text_field :name
  td.field
    = f.collection_select :city, InvestmentCity.all, :id, :name, { include_blank: true }, { class: 'select2' }
  td
    = f.select :village, {"#{village_name(f.object.village)}": "#{village_id(f.object.village)}"}, {}, { class: 'village-select' }
  td.field
    = f.collection_select :pole_base, InvestmentPoleBase.all, :id, :name, { include_blank: true }, { class: 'select2' }
  td.field
    = ""
  td.field
    = f.number_field "quantity_#{year}",
    class: "qc#{f.object.budget_investment.id}y#{year} group1-input",
    readonly: true
  td.field
    = f.hidden_field "unitary_amount_#{year}", value: (number_with_precision(eval("f.object.unitary_amount_#{year}"), precision: 2, separator: '.', delimiter: '') || 0)
    = text_field_tag '', number_with_precision(eval("f.object.unitary_amount_#{year}"), precision: 2), class: "uc#{f.object.budget_investment.id}y#{year} currency-input group1-input"|| 0, id: "uc#{f.object.id}y#{year}"
    = f.hidden_field :year_reference, value: "#{year}"
  td
  - if f.object.new_record?
    td
      = icon 'trash-o'
      = f.check_box :_destroy, class: "check_box-destroy new-record c#{f.object.budget_investment.id}y#{year}"
  - else
    td
      = icon 'trash-o'
      = f.check_box :_destroy, class: "check_box-destroy c#{f.object.budget_investment.id}y#{year}"

app/views/pdsis/_mapa.html.slim
h2 Território e população - Mapa

.field
  = f.file_field :map

app/views/pdsis/_processo_de_construcao_do_pdsi.html.slim
h2 O processo de construção do PDSI 2016-2019
.my-text
  h3
    | (Escreva aqui o seu texto)
  .field
    = f.text_area :processo_construcao_pdsi_2, { class: 'basic-editable' }
.sample-text
  h3
    | (Seu texto aparecerá no local marcado com [PARAGRAFO_DSEI])
  == @pdsi.sample :processo_construcao_pdsi_2

app/views/pdsis/_rede_servicos.html.slim
- @dsei.base_polos_with_service_networks.each do |base_polo|
  fieldset
    legend
      |Polo Base &nbsp;
      strong = base_polo.name

    = f.fields_for :service_networks, base_polo.force_service_networks(@pdsi) do |item|
      fieldset
        legend
          |Cidade&nbsp;
          strong = item.object.city_name

        fieldset
          legend Estabelecimentos de saúde (Complementariedade da Atenção Básica)

          table.table.nested-form
            thead
              tr
                th Nome
                th.destroy Apagar?

            - tbody_id = "tbody_establishment_#{item.object.id}"
            tbody id=(tbody_id)
              = item.fields_for :health_establishments do |health_establishment|
                = render 'health_establishment_fields', { f: health_establishment }
            tfoot
              tr
                td.links.right-align colspan="2"
                  = link_to_add_association item, :health_establishments, { data: { "association-insertion-node": "##{tbody_id}", "association-insertion-method": 'append' }, class: 'button btn-sm' } do
                    = icon 'plus'
                    | Adicionar Estabelecimento

        fieldset
          legend Estabelecimentos de saúde (Complementariedade da Atenção Básica)

          table.table.nested-form
            thead
              tr
                th Nome
                th.destroy Apagar?

            - tbody_id = "tbody_specialized_#{item.object.id}"
            tbody id=(tbody_id)
              = item.fields_for :health_specializeds do |health_specialized|
                = render 'health_specialized_fields', { f: health_specialized }
            tfoot
              tr
                td.links.right-align colspan="2"
                  = link_to_add_association item, :health_specializeds, { data: { "association-insertion-node": "##{tbody_id}", "association-insertion-method": 'append' }, class: 'button btn-sm' } do
                    = icon 'plus'
                    | Adicionar Estabelecimento

app/views/pdsis/edit.html.slim
= form_for @pdsi, url: pdsi_path(@pdsi, section: @section_url), html: { multipart: true } do |f|
  - if @pdsi.errors.any?
    #error_explanation.flash-error
      h2 = "#{pluralize(@pdsi.errors.count, "erro")} encontrados:"
      ul
        - @pdsi.errors.full_messages.each do |message|
          li = message

  .edit-section
    == render "pdsis/#{@section}/form", f: f

  .actions
    = hidden_field_tag :section, @section
    = hidden_field_tag :subsection, @subsection.gsub(/-/, '_') if @subsection

    a#pdsi_save_button.button href="javascript:void(0)" onclick="$(this).closest('form').submit()"
      i.fa.fa-save
      | Salvar

    | &nbsp;

    = link_to 'javascript:history.back()', class: 'button' do
      i.fa.fa-warning
      | Cancelar

app/views/pdsis/index.html.slim
= render "pdsis/sections/#{@section}"

app/views/pdsis/pdf_errors.html.slim
h1 Os ítems abaixo precisam ser preenchidos antes de gerar o PDF
ul
  - @errors.keys.each do |error|
    li
      = I18n.t(error)

app/views/pdsis/render_pdf.slim
<meta http-equiv="content-type" content="text/html; charset=utf-8" />

== wicked_pdf_stylesheet_link_tag "pdf"

.document
  section.alwaysbreak.cap.introducao
    == render 'pdsis/pdf/cap1'
  section.alwaysbreak.cap.processo
    == render 'pdsis/pdf/cap2'
  section.alwaysbreak.cap.caracterizacao
    == render 'pdsis/pdf/cap3'
  section.alwaysbreak.cap.analise
    == render 'pdsis/pdf/cap4'
  section.alwaysbreak.cap.resultado
    == render 'pdsis/pdf/cap5'
  section.alwaysbreak.cap.orcamento
    == render 'pdsis/pdf/cap6'
  section.alwaysbreak.anexo
    == render 'pdsis/pdf/cap7'

app/views/pdsis/show.html.slim
== render 'pdsis/indicadores_saude_indigena/show_casai'