config/routes.rb
Rails.application.routes.draw do
  resources :sesai_people,
            path: 'pessoas-sesai',
            path_names: { new: 'cadastrar', edit: 'alterar', destroy: 'excluir' }

  resources :people,
            path: 'pessoas',
            path_names: { new: 'cadastrar', edit: 'alterar', destroy: 'excluir' }

  resources :budget_correction_factors
  resources :costs
  resources :investments

  post '/image-upload',     to: 'application#image_upload', as: :image_upload
  post '/procurar-pessoa',  to: 'people#search',            as: :search
  post '/procurar-pessoa-com-dsei', to: 'people#search_with_dsei', as: :search_with_dsei

  get 'category_budgets/index'

  resources :results, path: 'resultados', path_names: { new: 'cadastrar', edit: 'alterar' }
  resources :casais, path_names: { new: 'cadastrar', edit: 'alterar' }
  resources :absolute_data, path: 'dados-absolutos', path_names: { new: 'cadastrar', edit: 'alterar' }

  get '/pdsis/show', to: 'pdsis#show'

  scope '/dotacao-orcamentaria' do
    get '/', to: 'category_budgets#index', as: :category_budgets
    get '/alterar/:id',
        to: 'pdsis#edit_category_budgets',
        as: :edit_category_budget, defaults: { section: 'dotacao_orcamentaria' }
  end

  scope '/meu-pdsi' do
    post '/:id/alterar/projecao-orcamentaria/editar-justificativa',
         to: 'budget_justifiers#edit_justifier',
         as: :budget_justifier_edit_justifier

    post '/:id/alterar/projecao-orcamentaria/new_budget_forecast_by_cost',
         to: 'pdsis#new_budget_forecast_by_cost',
         as: :new_budget_forecast_by_cost

    post '/:id/alterar/projecao-orcamentaria/novo-comentario',
         to: 'budget_forecasts#new_comment',
         as: :budget_forecast_new_comment

    post '/:id/alterar/projecao-orcamentaria/ver-comentario',
         to: 'budget_forecasts#see_comment',
         as: :budget_forecast_see_comment

    post '/:id/alterar/projecao-orcamentaria/deleta-comentario',
         to: 'budget_forecasts#delete_comment',
         as: :budget_forecast_delete_comment

    post '/:id/alterar/projecao-orcamentaria/investimento/novo-comentario',
         to: 'budget_investments#new_comment',
         as: :budget_investment_new_comment

    post '/:id/alterar/projecao-orcamentaria/investimento/ver-comentario',
         to: 'budget_investments#see_comment',
         as: :budget_investment_see_comment

    post '/:id/alterar/projecao-orcamentaria/investimento/deleta-comentario',
         to: 'budget_investments#delete_comment',
         as: :budget_investment_delete_comment

    post '/:id/alterar/projecao-orcamentaria/update_cost_name',
         to: 'pdsis#update_cost_name',
         as: :update_cost_name

    get '/:id/alterar/projecao-orcamentaria/:subsection',
        defaults: { section: 'projecao-orcamentaria' },
        to: 'pdsis#edit',
        as: :edit_budget_projection

    get '/:id/alterar/resultados-esperados/:subsection',
        defaults: { section: 'resultados-esperados', tab: 'resultados' },
        to: 'pdsis#edit',
        as: :edit_results

    get '/:id/alterar/resultados-esperados/responsabilidades/:subsection',
        defaults: { section: 'resultados-esperados', tab: 'responsabilidades' },
        to: 'pdsis#edit',
        as: :edit_responsabilities

    get '/(ver/:section)',                    to: 'pdsis#index',      as: :pdsis
    patch '/:id/alterar/:section',            to: 'pdsis#update',     as: :pdsi
    get '/:id/alterar/:section(/:base_polo)', to: 'pdsis#edit',       as: :edit_pdsi
    delete '/:id/mapa/excluir',               to: 'pdsis#delete_map', as: :delete_map

    get '/:id/alterar/anexos/dimensionamento-necessidades/:subsection',
        defaults: { section: 'anexos' },
        to: 'pdsis#edit',
        as: :edit_anexos

    scope '/dados-demograficos' do
      patch '/:id/alterar', to: 'demographic_datas#update', as: :demographic_data
      get '/:id/alterar', to: 'demographic_datas#edit', as: :edit_demographic_data
    end

    scope '/indicadores-saude-indigena', defaults: { section: 'indicadores-saude-indigena' } do
      get '/:id/:subsection/alterar(/polo-base/:base_polo)(/casai/:casai)',
          to: 'pdsis#health_indicators',
          as: :health_indicators
    end

    # Resultados Esperados
    get '/:id/resultados-esperados',
        to: 'results_special#index', as: :results_special

    post '/:id/resultados-esperados',
         to: 'results_special#update', as: :results_special_edit

    post '/:id/resultados-esperados/loop',
         to: 'results_special#loop', as: :results_special_loop

    post '/:id/resultados-esperados/respontabilidade',
         to: 'results_special#responsability', as: :results_special_responsability

    post '/:id/resultados-esperados/nao-se-aplica',
         to: 'results_special#false_result', as: :results_special_false_result

    post '/:id/resultados-esperados/novo-comentario',
         to: 'results_special#new_comment', as: :results_special_new_comment

    post '/:id/resultados-esperados/deleta-comentario',
         to: 'results_special#delete_comment', as: :results_special_delete_comment

    post '/:id/resultados-esperados/delete',
         to: 'results_special#delete', as: :results_special_delete

    post '/:id/resultados-esperados/associar-produto',
         to: 'results_special#link_product', as: :results_special_link_product

    post '/:id/resultados-esperados/associar-produto-dsei',
         to: 'results_special#link_product_dsei', as: :results_special_link_product_dsei

    post '/:id/resultados-esperados/resultado-especifico',
         to: 'results_special#specific_result', as: :results_special_specific_result

    post '/:id/resultados-esperados/resultado-especifico/atualizar',
         to: 'results_special#specific_update', as: :results_special_specific_update

    post '/:id/resultados-esperados/resultado-especifico/deletar',
         to: 'results_special#delete_specific_result', as: :results_special_delete_specific_result

    post '/:id/resultados-esperados/ordenar-produtos',
         to: 'results_special#products_order', as: :results_special_products_order

    post '/:id/resultados-esperados/ver-comentario',
         to: 'results_special#see_comment', as: :results_special_see_comment

    post '/:id/resultados-esperados/selecionar-links',
         to: 'results_special#get_all_related_links', as: :results_special_get_all_related_links
    post '/:id/resultados-esperados/retirar-link',
          to: 'results_special#remove_link', as: :results_special_remove_link

    # Resultados Específicos
    get '/:id/resultados-especificos',
        defaults: { section: 'resultados-esperados', tab: 'especificos' },
        to: 'specific_results#edit',
        as: :edit_specific_results

    patch '/:id/resultados-especificos',
          defaults: { section: 'resultados-esperados', tab: 'especificos' },
          to: 'specific_results#update',
          as: :update_specific_results
    get '/:id/pdf', to: 'pdsis#render_pdf', as: :print_pdf
    get '/:id/pdf_errors', to: 'pdsis#pdf_errors', as: :pdf_errors
  end

  scope '/templates' do
    get '/',                        to: 'text_templates#index',   as: :text_templates
    patch '/:id/alterar/:section',  to: 'text_templates#update',  as: :text_template
    get '/:id/alterar/:section',    to: 'text_templates#edit',    as: :edit_text_template
    get '/introducao-sesai',        to: 'text_templates#introducao_sesai', as: :introducao_sesai
    get '/analise-situacional-sesai', to: 'text_templates#analise_situacional_sesai', as: :analise_situacional_sesai
    get '/processo-de-construcao-sesai', to: 'text_templates#processo_de_construcao_sesai', as: :processo_de_construcao_sesai
  end

  devise_for :users, path: '', path_names: { sign_in: 'entrar',
                                             sign_out: 'sair',
                                             password: 'secret',
                                             confirmation: 'verification',
                                             unlock: 'unblock',
                                             registration: 'register',
                                             sign_up: 'cmon_let_me_in' }

  resources :users, path: 'usuarios', path_names: { new: 'cadastrar', edit: 'alterar' }

  get '/alterar-senha',   to: 'users#edit_password',    as: :edit_password
  patch '/alterar-senha', to: 'users#update_password',  as: :update_password

  # ApplicationController Routes
  get '/health', to: 'application#health'
  post '/selecionar-dsei',
       to: 'application#set_dsei_and_pdsi_to_sesai',
       as: :set_dsei_and_pdsi_to_sesai

  post '/limpar-dsei',
       to: 'application#unset_dsei_and_pdsi_to_sesai',
       as: :unset_dsei_and_pdsi_to_sesai

  scope '/locations' do
    get '/villages', to: 'locations#villages'
    get '/cities', to: 'locations#cities'
  end

  root 'users#home'
end

app/helpers/pdsis_helper.rb
module PdsisHelper

  def allowed_sections
    %w"dados-fisiograficos destinos rede-servicos indicadores-saude-indigena destinos capacidade-instalada"
  end

  def section_path(section)
    three = [{ name: '3. Caracterização do DSEI', path: pdsis_path('caracterizacao-do-dsei')}]
    bread = [{ name: section_name(section), path: pdsis_path(section: section.gsub(/_/, '-'))}]

    if %w"mapa dados_fisiograficos destinos capacidade_instalada rede_servicos infraestrutura_edificacoes infraestrutura_saneamento capais".include? section
      three + bread
    else
      bread
    end
  end

  def section_name(section)
    {
      introducao: '1. Introdução',
      processo_de_construcao_do_pdsi: '2. O Processo de construção do PDSI',
      # 3
      caracterizacao_do_dsei: '3. Caracterização do DSEI',
      mapa: '3.1. Mapa do Território',
      dados_fisiograficos: '3.1. Dados fisiográficos',
      destinos: '3.2. Meios de Transporte',
      recursos_humanos: '3.2. Dimensionamento da força de trabalho',
      capacidade_instalada: '3.2. Capacidade Instalada',
      rede_servicos: '3.2. Rede de serviços',
      infraestrutura_edificacoes: '3.2. Infraestrutura de saúde - Edificações',
      infraestrutura_saneamento:  '3.2. Infraestrutura de saúde - Saneamento',
      capais:        '3.2. Infraestrutura de saúde - CAPAIs',
      # 4
      analise_situacional:        '4. Análise situacional',
      indicadores_saude_indigena: '4.1 Indicadores estratégicos para a saúde indígena',
      principais_desafios:        '4.2 Principais desafios a serem enfrentados em 2016-2019',
      # 5
      resultados_esperados:   '5. Resultados esperados',
      # 6
      projecao_orcamentaria:  '6. Projeção orçamentária 2016-2019',
      dotacao_orcamentaria:   '6. Dotação orçamentária',
      # 7
      anexos: '7. Anexos',
    }[section.to_sym]
  end

  def sum_human_resources(pdsi)
    sum_actual(pdsi)
    sum_needed(pdsi)
  end

  private

  def sum_needed(pdsi)
    needed = pdsi.pdsi_human_resources.select(:id,
                                              :ubsi_necessaria,
                                              :polo_base_tipo_1_necessaria,
                                              :polo_base_tipo_2_necessaria,
                                              :casai_necessaria,
                                              :sead_necessaria,
                                              :selog_necessaria,
                                              :sesane_necessaria,
                                              :sead_necessaria,
                                              :sgep_necessaria,
                                              :gabinete_necessaria,
                                              :diasi_necessaria)
    needed.all.as_json.each do |nd|
      id = nil
      nd.slice('id').values.each { |e| id = e }
      sum = nd.except('id').values.reject(&:nil?).sum
      PdsiHumanResource.find(id).update_attribute(:workforce_needed, sum)
    end
  end

  def sum_actual(pdsi)
    actual = pdsi.pdsi_human_resources.select(:id,
                                              :ubsi_atual,
                                              :polo_base_tipo_1_atual,
                                              :polo_base_tipo_2_atual,
                                              :casai_atual,
                                              :sead_atual,
                                              :selog_atual,
                                              :sesane_atual,
                                              :seofi_atual,
                                              :sgep_atual,
                                              :gabinete_atual,
                                              :diasi_atual)
    actual.all.as_json.each do |ac|
      id = nil
      ac.slice('id').values.each { |e| id = e }
      sum = ac.except('id').values.reject(&:nil?).sum
      PdsiHumanResource.find(id).update_attribute(:actual_sum, sum)
    end
  end
end

app/views/pdsis/dados_fisiograficos/_etnias.html.slim
fieldset
  legend Etnias

  ul.how-to-use
    li Para adicionar uma nova Etnia clique no botão "Adicionar Etnia".
    li Coloque apenas uma etnia por campo de texto. Para inserir mais etnias, clique de novo no botão.
    li
      | Para apagar uma etnia inserida anteriormente, marque a caixinha na coluna "Apagar?".
      br
      | A etnia será apagada quando você clicar no botão "Salvar" do formulário.

  - tbody_id = "physiographic_data_ethnicities_#{f.object.id}"
  table.table.nested-form
    thead
      tr
        th Nome
        th.destroy Apagar?
    tbody id=(tbody_id)
      = f.fields_for :physiographic_data_ethnicities do |physiographic_data_ethnicity|
        = render 'pdsis/dados_fisiograficos/physiographic_data_ethnicity_fields', { f: physiographic_data_ethnicity }
    tfoot
      tr
        td.links.right-align colspan="2"
          = link_to_add_association f, :physiographic_data_ethnicities, { data: { "association-insertion-node": "##{tbody_id}", "association-insertion-method": 'append' }, class: 'button btn-sm', partial: 'pdsis/dados_fisiograficos/physiographic_data_ethnicity_fields' } do
            = icon 'plus'
            | Adicionar Etnia

app/views/pdsis/dados_fisiograficos/_form.html.slim
- content_for :breadcrumb do
  = breadcrumbs [{ name: '3. Caracterização do DSEI', path: pdsis_path(section: 'caracterizacao-do-dsei')}, { name: '3.1.C - Dados Fisiográficos', path: nil}]

h1 POLO BASE: #{@base_polo.name}

= render 'hidden_fields'

.vertical-tabs-container
  .vertical-tabs style="width: 30%;"
    - @dsei.base_polos.order(:id).each do |base_polo|
      - link_opt = [{ class: 'vertical-tab' }, {:selected_class => 'is-active'}]
      = nav_link_to edit_pdsi_path(@pdsi, section: 'dados-fisiograficos', base_polo: base_polo), link_opt[0], link_opt[1] do
        = base_polo.name
  .vertical-tab-content-container style="width: 70%;"
    .vertical-tab-content style="display: block;"
      fieldset
        legend
          |Polo Base &nbsp;
          strong = @base_polo.name

        = f.fields_for :pdsi_base_polo_data, @base_polo.pdsi_data(@pdsi) do |item|
          = item.hidden_field :base_polo_id

          .field
            = item.label 'Município do Polo Base'
            = item.text_field :city_name, { readonly: true }

        - @base_polo.villages.includes(:physiographic_data).each do |village|
          fieldset
            legend
              | Aldeia&nbsp;
              strong = village.name
            = f.fields_for :physiographic_datas, village.physiographic_datum(@pdsi) do |item|
              == render 'pdsis/dados_fisiograficos/form_aldeias', f: item

app/views/pdsis/dados_fisiograficos/_form_aldeias.html.slim
= f.hidden_field :village_id
= f.hidden_field :pdsi_id, value: @pdsi.id

.field
  = f.label  :city_name
  = f.select :city_name, {"#{f.object.city_name}": f.object.city_name}, {}, { class: 'city-select' }
br

.village-population
  .field.inline_field
    h3 Homens

    .inline_line
      .value
        = f.label :m_1
      .value
        = f.label :m_1_4
      .value
        = f.label :m_5_9
      .value
        = f.label :m_10_49
      .value
        = f.label :m_50_59
      .value
        = f.label :m_60
    .inline_line
      .value
        = f.number_field :m_1, class: 'population-count'
      .value
        = f.number_field :m_1_4, class: 'population-count'
      .value
        = f.number_field :m_5_9, class: 'population-count'
      .value
        = f.number_field :m_10_49, class: 'population-count'
      .value
        = f.number_field :m_50_59, class: 'population-count'
      .value
        = f.number_field :m_60, class: 'population-count'

  .field.inline_field
    h3 Mulheres

    .inline_line
      .value
        = f.label :w_1
      .value
        = f.label :w_1_4
      .value
        = f.label :w_5_9
      .value
        = f.label :w_10_49
      .value
        = f.label :w_50_59
      .value
        = f.label :w_60
    .inline_line
      .value
        = f.number_field :w_1, class: 'population-count'
      .value
        = f.number_field :w_1_4, class: 'population-count'
      .value
        = f.number_field :w_5_9, class: 'population-count'
      .value
        = f.number_field :w_10_49, class: 'population-count'
      .value
        = f.number_field :w_50_59, class: 'population-count'
      .value
        = f.number_field :w_60, class: 'population-count'
    .inline_line
      = f.label 'População total'
      = f.text_field :village_population, class: 'population-total', readonly: true

= render 'pdsis/dados_fisiograficos/etnias',  f: f
= render 'pdsis/dados_fisiograficos/idiomas', f: f

.field
  = f.label :pt_fluency, class: 'checkbox'
  label.checkbox
    = f.radio_button :pt_fluency, 'Plena'
    | Plena
    span.description Comunidades em que toda a população tem pleno domínio da língua portuguesa.
  label.checkbox
    = f.radio_button :pt_fluency, 'Suficiente'
    | Suficiente
    span.description Comunidades em que a maior parte da população consegue se comunicar em português, ainda que cotidianamente se comuniquem  através de línguas indígena. Em situações específicas pode ser necessário o apoio de intérprete para a realização de ações de saúde com certos grupos.
  label.checkbox
    = f.radio_button :pt_fluency, 'Parcial'
    | Parcial
    span.description Comunidades em que parcela importante da população (por exemplo mulheres e/ou crianças) não entende ou tem dificuldades em se comunicar em português, motivo pelo qual é necessário o apoio de intérprete para a realização de ações de saúde.
  label.checkbox
    = f.radio_button :pt_fluency, 'Limitada'
    | Limitada
    span.description Comunidades onde a comunicação em português é muito limitada ou inexistente, fazendo-se necessário apoio de intérprete para a realização de todas as ações de saúde.

app/views/pdsis/dados_fisiograficos/_idiomas.html.slim
fieldset
  legend Língua

  ul.how-to-use
    li Para adicionar uma nova Língua Indígena clique no botão "Adicionar Língua Indígena".
    li Coloque apenas um idioma por campo de texto. Para inserir mais línguas, clique de novo no botão.
    li
      | Para apagar uma língua inserida anteriormente, marque a caixinha na coluna "Apagar?".
      br
      | O idioma será apagado quando você clicar no botão "Salvar" do formulário.

  - tbody_id = "physiographic_data_languages_#{f.object.id}"
  table.table.nested-form
    thead
      tr
        th Insira apenas uma língua por campo
        th.destroy Apagar?
    tbody id=(tbody_id)
      = f.fields_for :physiographic_data_languages do |physiographic_data_language|
        = render 'pdsis/dados_fisiograficos/physiographic_data_language_fields', { f: physiographic_data_language }
    tfoot
      tr
        td.links.right-align colspan="2"
          = link_to_add_association f, :physiographic_data_languages, { data: { "association-insertion-node": "##{tbody_id}", "association-insertion-method": 'append' }, class: 'button btn-sm', partial: 'pdsis/dados_fisiograficos/physiographic_data_language_fields' } do
            = icon 'plus'
            | Adicionar Língua

app/views/pdsis/dados_fisiograficos/_physiographic_data_ethnicity_fields.html.slim
tr.nested-fields
  td.field
    = f.collection_select :ethnicity_id, Ethnicity.all.order(:name), :id, :name, { include_blank: true }
  td.field.destroy
    = icon 'trash-o remove'
    .hidden
      = f.check_box :_destroy, class: 'remove-chk'

app/views/pdsis/dados_fisiograficos/_physiographic_data_language_fields.html.slim
tr.nested-fields
  td.field
    = f.text_field :language
  td.field.destroy
    = icon 'trash-o remove'
    .hidden
      = f.check_box :_destroy, class: 'remove-chk'

app/views/pdsis/dados_fisiograficos/_show.html.slim
- @dsei.base_polos_with_physiographic_data.order(:id).each do |base_polo|
  h1 Polo base: #{base_polo.name}
  table.tables.pdsi-fisiographic-data
    thead
      tr
        th[rowspan="2" style="width: 95px;"] Aldeia
        th[rowspan="2"] Etnia(s)
        th[rowspan="2"] Fluência em português
        th[rowspan="2"] Lingua Indígena
        th[colspan="6" style="border-bottom: 1px solid #ddd;"] Homens
        th[colspan="6" style="border-bottom: 1px solid #ddd;"] Mulheres
        th[rowspan="2"] População da aldeia
      tr
        th[style="border-left: 1px solid #ddd;"] < 1
        th 1-4
        th 5-9
        th 10-49
        th 50-59
        th ≥ 60
        th < 1
        th 1-4
        th 5-9
        th 10-49
        th 50-59
        th ≥ 60
    tbody
    - base_polo.villages.each do |village|
      - if village.physiographic_data
        tr
          td = village.name
          td
            - village.physiographic_data.physiographic_data_ethnicities.each do |e|
              = ethnicity_name(e.ethnicity_id)
              | ,
          td = village.physiographic_data.pt_fluency
          td
            - village.physiographic_data.physiographic_data_languages.each do |language|
              = language.language
              | ,
          td = village.physiographic_data.m_1
          td = village.physiographic_data.m_1_4
          td = village.physiographic_data.m_5_9
          td = village.physiographic_data.m_10_49
          td = village.physiographic_data.m_50_59
          td = village.physiographic_data.m_60
          td = village.physiographic_data.w_1
          td = village.physiographic_data.w_1_4
          td = village.physiographic_data.w_5_9
          td = village.physiographic_data.w_10_49
          td = village.physiographic_data.w_50_59
          td = village.physiographic_data.w_60
          td = village.physiographic_data.village_population
      - else
        tr
          td = village.name
          td
          td
          td
          td
          td
          td
          td
          td
          td
          td
          td
          td
          td
          td
          td
          td