config/routes.rb
Rails.application.routes.draw do
  resources :sesai_people,
            path: 'pessoas-sesai',
            path_names: { new: 'cadastrar', edit: 'alterar', destroy: 'excluir' }

  resources :people,
            path: 'pessoas',
            path_names: { new: 'cadastrar', edit: 'alterar', destroy: 'excluir' }

  resources :budget_correction_factors
  resources :costs
  resources :investments

  post '/image-upload',     to: 'application#image_upload', as: :image_upload
  post '/procurar-pessoa',  to: 'people#search',            as: :search
  post '/procurar-pessoa-com-dsei', to: 'people#search_with_dsei', as: :search_with_dsei

  get 'category_budgets/index'

  resources :results, path: 'resultados', path_names: { new: 'cadastrar', edit: 'alterar' }
  resources :casais, path_names: { new: 'cadastrar', edit: 'alterar' }
  resources :absolute_data, path: 'dados-absolutos', path_names: { new: 'cadastrar', edit: 'alterar' }

  get '/pdsis/show', to: 'pdsis#show'

  scope '/dotacao-orcamentaria' do
    get '/', to: 'category_budgets#index', as: :category_budgets
    get '/alterar/:id',
        to: 'pdsis#edit_category_budgets',
        as: :edit_category_budget, defaults: { section: 'dotacao_orcamentaria' }
  end

  scope '/meu-pdsi' do
    post '/:id/alterar/projecao-orcamentaria/editar-justificativa',
         to: 'budget_justifiers#edit_justifier',
         as: :budget_justifier_edit_justifier

    post '/:id/alterar/projecao-orcamentaria/new_budget_forecast_by_cost',
         to: 'pdsis#new_budget_forecast_by_cost',
         as: :new_budget_forecast_by_cost

    post '/:id/alterar/projecao-orcamentaria/novo-comentario',
         to: 'budget_forecasts#new_comment',
         as: :budget_forecast_new_comment

    post '/:id/alterar/projecao-orcamentaria/ver-comentario',
         to: 'budget_forecasts#see_comment',
         as: :budget_forecast_see_comment

    post '/:id/alterar/projecao-orcamentaria/deleta-comentario',
         to: 'budget_forecasts#delete_comment',
         as: :budget_forecast_delete_comment

    post '/:id/alterar/projecao-orcamentaria/investimento/novo-comentario',
         to: 'budget_investments#new_comment',
         as: :budget_investment_new_comment

    post '/:id/alterar/projecao-orcamentaria/investimento/ver-comentario',
         to: 'budget_investments#see_comment',
         as: :budget_investment_see_comment

    post '/:id/alterar/projecao-orcamentaria/investimento/deleta-comentario',
         to: 'budget_investments#delete_comment',
         as: :budget_investment_delete_comment

    post '/:id/alterar/projecao-orcamentaria/update_cost_name',
         to: 'pdsis#update_cost_name',
         as: :update_cost_name

    get '/:id/alterar/projecao-orcamentaria/:subsection',
        defaults: { section: 'projecao-orcamentaria' },
        to: 'pdsis#edit',
        as: :edit_budget_projection

    get '/:id/alterar/resultados-esperados/:subsection',
        defaults: { section: 'resultados-esperados', tab: 'resultados' },
        to: 'pdsis#edit',
        as: :edit_results

    get '/:id/alterar/resultados-esperados/responsabilidades/:subsection',
        defaults: { section: 'resultados-esperados', tab: 'responsabilidades' },
        to: 'pdsis#edit',
        as: :edit_responsabilities

    get '/(ver/:section)',                    to: 'pdsis#index',      as: :pdsis
    patch '/:id/alterar/:section',            to: 'pdsis#update',     as: :pdsi
    get '/:id/alterar/:section(/:base_polo)', to: 'pdsis#edit',       as: :edit_pdsi
    delete '/:id/mapa/excluir',               to: 'pdsis#delete_map', as: :delete_map

    get '/:id/alterar/anexos/dimensionamento-necessidades/:subsection',
        defaults: { section: 'anexos' },
        to: 'pdsis#edit',
        as: :edit_anexos

    scope '/dados-demograficos' do
      patch '/:id/alterar', to: 'demographic_datas#update', as: :demographic_data
      get '/:id/alterar', to: 'demographic_datas#edit', as: :edit_demographic_data
    end

    scope '/indicadores-saude-indigena', defaults: { section: 'indicadores-saude-indigena' } do
      get '/:id/:subsection/alterar(/polo-base/:base_polo)(/casai/:casai)',
          to: 'pdsis#health_indicators',
          as: :health_indicators
    end

    # Resultados Esperados
    get '/:id/resultados-esperados',
        to: 'results_special#index', as: :results_special

    post '/:id/resultados-esperados',
         to: 'results_special#update', as: :results_special_edit

    post '/:id/resultados-esperados/loop',
         to: 'results_special#loop', as: :results_special_loop

    post '/:id/resultados-esperados/respontabilidade',
         to: 'results_special#responsability', as: :results_special_responsability

    post '/:id/resultados-esperados/nao-se-aplica',
         to: 'results_special#false_result', as: :results_special_false_result

    post '/:id/resultados-esperados/novo-comentario',
         to: 'results_special#new_comment', as: :results_special_new_comment

    post '/:id/resultados-esperados/deleta-comentario',
         to: 'results_special#delete_comment', as: :results_special_delete_comment

    post '/:id/resultados-esperados/delete',
         to: 'results_special#delete', as: :results_special_delete

    post '/:id/resultados-esperados/associar-produto',
         to: 'results_special#link_product', as: :results_special_link_product

    post '/:id/resultados-esperados/associar-produto-dsei',
         to: 'results_special#link_product_dsei', as: :results_special_link_product_dsei

    post '/:id/resultados-esperados/resultado-especifico',
         to: 'results_special#specific_result', as: :results_special_specific_result

    post '/:id/resultados-esperados/resultado-especifico/atualizar',
         to: 'results_special#specific_update', as: :results_special_specific_update

    post '/:id/resultados-esperados/resultado-especifico/deletar',
         to: 'results_special#delete_specific_result', as: :results_special_delete_specific_result

    post '/:id/resultados-esperados/ordenar-produtos',
         to: 'results_special#products_order', as: :results_special_products_order

    post '/:id/resultados-esperados/ver-comentario',
         to: 'results_special#see_comment', as: :results_special_see_comment

    post '/:id/resultados-esperados/selecionar-links',
         to: 'results_special#get_all_related_links', as: :results_special_get_all_related_links
    post '/:id/resultados-esperados/retirar-link',
          to: 'results_special#remove_link', as: :results_special_remove_link

    # Resultados Específicos
    get '/:id/resultados-especificos',
        defaults: { section: 'resultados-esperados', tab: 'especificos' },
        to: 'specific_results#edit',
        as: :edit_specific_results

    patch '/:id/resultados-especificos',
          defaults: { section: 'resultados-esperados', tab: 'especificos' },
          to: 'specific_results#update',
          as: :update_specific_results
    get '/:id/pdf', to: 'pdsis#render_pdf', as: :print_pdf
    get '/:id/pdf_errors', to: 'pdsis#pdf_errors', as: :pdf_errors
  end

  scope '/templates' do
    get '/',                        to: 'text_templates#index',   as: :text_templates
    patch '/:id/alterar/:section',  to: 'text_templates#update',  as: :text_template
    get '/:id/alterar/:section',    to: 'text_templates#edit',    as: :edit_text_template
    get '/introducao-sesai',        to: 'text_templates#introducao_sesai', as: :introducao_sesai
    get '/analise-situacional-sesai', to: 'text_templates#analise_situacional_sesai', as: :analise_situacional_sesai
    get '/processo-de-construcao-sesai', to: 'text_templates#processo_de_construcao_sesai', as: :processo_de_construcao_sesai
  end

  devise_for :users, path: '', path_names: { sign_in: 'entrar',
                                             sign_out: 'sair',
                                             password: 'secret',
                                             confirmation: 'verification',
                                             unlock: 'unblock',
                                             registration: 'register',
                                             sign_up: 'cmon_let_me_in' }

  resources :users, path: 'usuarios', path_names: { new: 'cadastrar', edit: 'alterar' }

  get '/alterar-senha',   to: 'users#edit_password',    as: :edit_password
  patch '/alterar-senha', to: 'users#update_password',  as: :update_password

  # ApplicationController Routes
  get '/health', to: 'application#health'
  post '/selecionar-dsei',
       to: 'application#set_dsei_and_pdsi_to_sesai',
       as: :set_dsei_and_pdsi_to_sesai

  post '/limpar-dsei',
       to: 'application#unset_dsei_and_pdsi_to_sesai',
       as: :unset_dsei_and_pdsi_to_sesai

  scope '/locations' do
    get '/villages', to: 'locations#villages'
    get '/cities', to: 'locations#cities'
  end

  root 'users#home'
end

app/models/demographic_data.rb
class DemographicData < ActiveRecord::Base
  auditable
  include ActionView::Helpers::NumberHelper

  belongs_to :pdsi

  validates :extensao_territorial,  length: { maximum: 255 }, presence: false
  validates :municipio_sede,        length: { maximum: 255 }, presence: false
  validates :endereco,              length: { maximum: 255 }, presence: false

  validates_presence_of :numero_sede_polos_base, :numero_ubsi

  def extensao_territorial_km
    number_to_human(extensao_territorial.to_f, precision: 5, separator: '.',
                                               units: { unit: 'metros', thousand: 'km²' })
  end
end

app/controllers/demographic_datas_controller.rb
class DemographicDatasController < ApplicationController
  before_action :set_demographic_data#, only: [:show, :edit, :update, :destroy]

  # GET /demographic_datas
  def index
    @demographic_datas = DemographicData.all
  end

  # GET /demographic_datas/1/edit
  def edit
  end

  # PATCH/PUT /demographic_datas/1
  def update
    if @demographic_data.update(demographic_data_params)
      redirect_to edit_demographic_data_path(@demographic_data), notice: 'Dados atualizados com sucesso.'
    else
      render :edit
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demographic_data
      @demographic_data = current_pdsi.demographic_data
    end

    # Only allow a trusted parameter "white list" through.
    def demographic_data_params
      params
        .require(:demographic_data)
        .permit(:pdsi_id, :extensao_territorial, :municipio_sede,
                :endereco, :email, :numero_municipios, :populacao_indigena,
                :numero_polos_base, :numero_ubsi, :numero_regioes_de_saude,
                :numero_casais, :numero_aldeias, :numero_familias, :fluvial,
                :rodoviario, :aereo, :headquarters, :numero_sede_polos_base,
                etnias_attributes: [:id, :name, :_destroy])
    end
end

app/helpers/demographic_datas_helper.rb
module DemographicDatasHelper
  def has_transportation(obj, attr)
    response  = eval "obj.#{attr}"

    icon  = response ? 'check' : 'close'
    str   = response ? 'sim' : 'não'

    "&nbsp; <i class='fa fa-#{icon}'></i> #{str}"
  end

  def has_transportation_print(obj, attr)
    response  = eval "obj.#{attr}"

    str   = response ? "#{attr}" : ' '
    
    "#{str.capitalize} "
  end

  def ethnicity_name(id)
    Ethnicity.find(id).name
  end

  def select_city_name(city_string)
    City
      .find(city_string.to_i)
      .city unless city_string.nil? || city_string.empty?
  end

  def select_city_id(city_string)
    City
      .find(city_string.to_i)
      .id unless city_string.nil? || city_string.empty?
  end
end

app/views/demographic_datas/_form.html.slim
.field
  = f.label :extensao_territorial
  = f.text_field :extensao_territorial, readonly: true
.field
  = f.label :municipio_sede
  = f.text_field :municipio_sede, readonly: true
.field
  = f.label :endereco
  = f.text_field :endereco, readonly: true
.field
  = f.label :email
  = f.text_field :email, readonly: true
.field
  = f.label :numero_municipios
  = f.number_field :numero_municipios, readonly: true
.field
  = f.label :populacao_indigena
  = f.number_field :populacao_indigena, readonly: true

fieldset

  legend Etnias
  - if dsei_ethnicities(f.object.pdsi.dsei).blank?
    | Não informado
  - else
    = dsei_ethnicities(f.object.pdsi.dsei).map { |item| item }.join ', '

.field
  = f.label :numero_polos_base
  = f.number_field :numero_polos_base, readonly: true
.field
  = f.label :numero_sede_polos_base
  = f.number_field :numero_sede_polos_base
.field
  = f.label :numero_ubsi
  = f.number_field :numero_ubsi
.field
  = f.label :numero_regioes_de_saude
  = f.number_field :numero_regioes_de_saude,:readonly => true
.field
  = f.label :numero_casais
  = f.number_field :numero_casais,:readonly => true
.field
  = f.label :numero_aldeias
  = f.number_field :numero_aldeias,:readonly => true
.field
  = f.label :numero_familias
  = f.number_field :numero_familias,:readonly => true

fieldset
  legend Meios de Transporte

  p
    .field
      = f.label :fluvial
      = f.check_box :fluvial

  p
    .field
      = f.label :rodoviario
      = f.check_box :rodoviario

  p
  .field
      = f.label :aereo
      = f.check_box :aereo

app/views/demographic_datas/_show.html.slim
p
  strong #{DemographicData.human_attribute_name 'extensao_territorial'}:
  br
  = @demographic_data.extensao_territorial_km || 'Não informado'

p
  strong #{DemographicData.human_attribute_name 'municipio_sede'}:
  br
  = @demographic_data.municipio_sede || 'Não informado'

p
  strong #{DemographicData.human_attribute_name 'endereco'}:
  br
  = @demographic_data.endereco || 'Não informado'

p
  strong #{DemographicData.human_attribute_name 'email'}:
  br
  = @demographic_data.email || 'Não informado'

p
  strong #{DemographicData.human_attribute_name 'numero_municipios'}:
  br
  = @demographic_data.numero_municipios || 'Não informado'

p
  strong #{DemographicData.human_attribute_name 'populacao_indigena'}:
  br
  = @demographic_data.populacao_indigena || 'Não informado'

p
  strong #{DemographicData.human_attribute_name 'etnias'}:
  br
  - if dsei_ethnicities(@dsei).blank?
    | Não informado
  - else
    = dsei_ethnicities(@dsei).map { |item| item }.join(', ')

p
  strong #{DemographicData.human_attribute_name 'numero_polos_base'}:
  br
  = @demographic_data.numero_polos_base || 'Não informado'

p
  strong Nº de Sede de Polos Base
  br
  = @demographic_data.headquarters || 'Não informado'

p
  strong #{DemographicData.human_attribute_name 'numero_ubsi'}:
  br
  = @demographic_data.numero_ubsi || 'Não informado'

p
  strong #{DemographicData.human_attribute_name 'numero_regioes_de_saude'}:
  br
  = @demographic_data.numero_regioes_de_saude || 'Não informado'

p
  strong #{DemographicData.human_attribute_name 'numero_casais'}:
  br
  = @demographic_data.numero_casais || 'Não informado'

p
  strong #{DemographicData.human_attribute_name 'numero_aldeias'}:
  br
  = @demographic_data.numero_aldeias || 'Não informado'

p
  strong #{DemographicData.human_attribute_name 'numero_familias'}:
  br
  = @demographic_data.numero_familias || 'Não informado'

fieldset
  legend #{DemographicData.human_attribute_name 'meios_de_transporte'}:

  p
    strong #{DemographicData.human_attribute_name 'fluvial'}:
    == has_transportation @demographic_data, :fluvial
  p
    strong #{DemographicData.human_attribute_name 'rodoviario'}:
    == has_transportation @demographic_data, :rodoviario
  p
    strong #{DemographicData.human_attribute_name 'aereo'}:
    == has_transportation @demographic_data, :aereo

app/views/demographic_datas/_transportation_fields.html.slim
tr.nested-fields
  td.field
    = f.text_field :name
  td.field.destroy
    = f.check_box :_destroy

app/views/demographic_datas/edit.html.slim
- content_for :breadcrumb do
  = breadcrumbs [{ name: '3. Caracterização do DSEI', path: pdsis_path(section: 'caracterizacao-do-dsei')}, { name: '3.1.B - Dados Demográficos', path: nil }]

= form_for @demographic_data do |f|
  - if @demographic_data.errors.any?
    #error_explanation.flash-error
      h2 = "#{pluralize(@demographic_data.errors.count, "error")} encontrados"
      ul
        - @demographic_data.errors.full_messages.each do |message|
          li = message

  fieldset
    == render 'form', f: f

  .actions
    a.button href="javascript:void(0)" onclick="$(this).closest('form').submit()"
      i.fa.fa-save
      | Salvar

    | &nbsp;

    = link_to 'javascript:history.back()', class: 'button' do
      i.fa.fa-warning
      | Cancelar

app/views/demographic_datas/index.html.slim
== render 'show'